version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: lwt_manwhitdb_01
      POSTGRES_USER: lwt_manwhit_01
      POSTGRES_PASSWORD: lemonwares
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://lwt_manwhit_01:lemonwares@postgres:5432/lwt_manwhitdb_01
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
